strictness: veryhigh

test-warnings: true

autodetect: yes

ignore-paths:
    - runtests.py
    - ch02/bytecode/

ignore-patterns:
    # Ignore everything is not in chXX/practice
    - ^ch[0-9]{2}/([a-z0-9_]*)\.py$

pylint:
    disable:
        - invalid-name

python-targets:
    - 3
