sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "nightly"

install:
  - pip install pytest
  - pip install coveralls

script: coverage run --pylib --include=`pwd`/ch*  runtests.py

after_success: coveralls

notifications:
  email: true
